# -*- coding: utf-8 -*-
#genarate all programms.csv file
import csv

# Define the data categorized by level
data = {
    "Doctorate": [
        "Doctor of Philosophy in Environmental Science",
        "Doctor of Philosophy in Agricultural Extension",
        "Doctor of Philosophy in Agribusiness Management",
        "Doctor of Philosophy in Agricultural Economics",
        "Doctor of Philosophy in Soil Science",
        "Doctor of Philosophy in Horticulture",
        "Doctor of Philosophy in Genetics and Plant Breeding",
        "Doctor of Philosophy in Agronomy",
        "Doctor of Philosophy in Animal Science",
        "Doctor of Philosophy in Fine Art",
        "Doctor of Philosophy in Interior Design",
        "Doctor of Philosophy in Linguistics",
        "Doctor of Philosophy in Kiswahili",
        "Doctor of Philosophy in Mass Communication",
        "Doctor of Philosophy in Literature",
        "Doctor of Philosophy in Sociology",
        "Doctor of Philosophy in Anthropology",
        "Doctor of Philosophy in Counselling Psychology",
        "Doctor of Philosophy in French",
        "Doctor of Philosophy in Religion",
        "Doctor of Philosophy in Philosophy",
        "Doctor of Philosophy in Geography",
        "Doctor of Philosophy in Textile and Fashion Design",
        "Doctor of Philosophy in Communication and Media Studies",
        "Doctor of Philosophy in Theology",
        "Doctor of Philosophy in History",
        "Doctor of Philosophy in Music",
        "Doctor of Philosophy in French Studies",
        "Doctor of Philosophy in Design",
        "Doctor of Philosophy in Accounting",
        "Doctor of Philosophy in Finance",
        "Doctor of Philosophy in Tourism Management",
        "Doctor of Philosophy in Hospitality Management",
        "Doctor of Philosophy in Economics",
        "Doctor of Philosophy in Management Information Systems",
        "Doctor of Philosophy in Operations Management",
        "Doctor of Philosophy in Procurement and Supply Chain Management",
        "Doctor of Philosophy in Business Administration",
        "Doctor of Philosophy in Economics",
        "Doctor of Philosophy in Strategic Management",
        "Doctor of Philosophy in Marketing",
        "Doctor of Philosophy in Human Resource Management",
        "Doctor of Philosophy in Accounting",
        "Doctor of Philosophy in Finance",
        "Doctor of Philosophy in Tourism Management",
        "Doctor of Philosophy in Hospitality Management",
        "Doctor of Philosophy in Economics",
        "Doctor of Philosophy in Management Information Systems",
        "Doctor of Philosophy in Operations Management",
        "Doctor of Philosophy in Procurement and Supply Chain Management",
        "Doctor of Philosophy in Business Administration",
        "Doctor of Philosophy in Economics",
        "Doctor of Philosophy in Strategic Management",
        "Doctor of Philosophy in Marketing",
        "Doctor of Philosophy in Human Resource Management",
        "Doctor of Philosophy in Curriculum Studies",
        "Doctor of Philosophy in Educational Technology",
        "Doctor of Philosophy in Pedagogy Educational Administration",
        "Doctor of Philosophy in Educational Psychology",
        "Doctor of Philosophy in Guidance and Counselling",
        "Doctor of Philosophy in Planning and Economics of Education",
        "Doctor of Philosophy in Special Needs Education",
        "Doctor of Philosophy in Educational Administration",
        "Doctor of Philosophy in Planning and Economics of Education",
        "Doctor of Philosophy in Political Science",
        "Doctor of Philosophy in International Relations",
        "Doctor of Philosophy in Development Studies",
        "Doctor of Philosophy in Entrepreneurship and Development",
        "Doctor of Philosophy in Gender Studies",
        "Doctor of Philosophy in Gender and Development",
        "Doctor of Philosophy in Planning",
        "Doctor of Philosophy in Biomedical Sciences",
        "Doctor of Philosophy in Community Nutrition and Development",
        "Doctor of Philosophy in Public Health Nutrition",
        "Doctor of Philosophy in Public Health",
        "Doctor of Philosophy in Medical Entomology and Vector Science",
        "Doctor of Philosophy in Pharmacology",
        "Doctor of Philosophy in Medical Parasitology",
        "Doctor of Philosophy in Medical Microbiology",
        "Doctor of Philosophy in Medical Immunology",
        "Doctor of Philosophy in Medical Genetics",
        "Doctor of Philosophy in Computational Biology and Bioinformatics",
        "Doctor of Philosophy in Medical Biotechnology",
        "Doctor of Philosophy in Chemistry",
        "Doctor of Philosophy in Physics",
        "Doctor of Philosophy in Botany",
        "Doctor of Philosophy in Aquatic Sciences",
        "Doctor of Philosophy in Cell and Molecular Biology",
        "Doctor of Philosophy in Conservation Biology",
        "Doctor of Philosophy in Molecular Microbiology and Biotechnology",
        "Doctor of Philosophy in Parasitology and Vector Biology",
        "Doctor of Philosophy in Entomology",
        "Doctor of Philosophy in Applied Statistics",
        "Doctor of Philosophy in Pure Mathematics",
        "Doctor of Philosophy in Applied Mathematics",
        "Doctor of Philosophy in Computer Science",
        "Doctor of Philosophy in Information Technology",
        "Doctor of Philosophy in Computer Technology",
        "Doctor of Philosophy in Information Systems"
    ],
    "Masters": [
        "Master of Science in Animal Science",
        "Master of Science in Agricultural Economics",
        "Master of Science in Agricultural Extension",
        "Master of Science in Soil Science",
        "Master of Science in Agri-Business Management",
        "Master of Science in Agronomy",
        "Master of Science in Genetics and Plant Breeding",
        "Master of Science in Urban Environmental Planning and Management",
        "Master of Science in Environmental Sciences",
        "Master of Arts in Fine Art",
        "Master of Arts in Interior Design",
        "Master of Arts in Linguistics",
        "Master of Arts in Theoretical Linguistics",
        "Master of Arts in Applied Linguistics",
        "Master of Arts in Kiswahili Studies",
        "Masters in Communication and Media",
        "Master of Arts in Literature",
        "Masters of Arts Sociology",
        "Masters of Arts Social Policy",
        "Masters of Arts Anthropology",
        "Master of Arts in Counselling Psychology",
        "Masters of Arts (French Studies)",
        "Master of Arts in Religion",
        "Master of Arts in Philosophy",
        "Master of Arts in Fine Art",
        "Masters of Arts in Interior Design",
        "Master of Arts in Geography",
        "Master of Arts in Music",
        "Master of Arts in Communication and Media Studies",
        "Master of Arts in Anthropology",
        "Master of Arts in Sociology",
        "Master in Social Development and Management",
        "Master in Arts Social Policy",
        "Master of Arts in Social Science Research Methods",
        "Master of Arts in Kiswahili",
        "Master of Arts in Gender Studies",
        "Master of Arts in Gender and Development",
        "Master of Arts in History",
        "Master of Arts in Psychology",
        "Master of Arts in Counselling Psychology",
        "Master of Arts in French Studies",
        "Master of Arts in Fashion Design",
        "Master of Science in Finance",
        "Masters of Business Administration (MBA)",
        "Masters of Science Human Resource Management",
        "Masters in Business Entrepreneurship",
        "Master of Science in Eco-Tourism Management",
        "Master of Science in Tourism Management",
        "Master of Science in Hospitality Management",
        "Master of Economics (Economic Policy Analysis and Management)",
        "Master of Economics (Applied Economics)",
        "Master of Arts in Economics",
        "Master of Science in Supply Chain Management",
        "Master of Education in Special Needs Education",
        "Master of Education in Curriculum Studies",
        "Master of Education in Pedagogy",
        "Master of Education in Educational Planning and Economics",
        "Master of Education in Educational Administration",
        "Master of Education in Educational Technology",
        "Master of Education in Educational Psychology",
        "Master of Education in Guidance and Counselling",
        "Master of Education in Early Childhood Education Development",
        "Master of Education in Planning and Economics of Education",
        "Master of Arts in Research and Public Policy (MRPP)",
        "Master of Arts in International Relations",
        "Master of Arts in Political Science",
        "Master of Research and Public Policy",
        "Master of Arts in Development Studies",
        "Master of Arts in Research and Public Policy",
        "Master of Arts in Urban Development and Management",
        "Master of Arts in Monitoring and Evaluation",
        "Master of Arts in Project Planning and Management",
        "Master of Medicine (MMed) in Family and Emergency Medicine",
        "Master of Medicine (MMed) in General Surgery",
        "Master of Medicine in Obstetrics and Gynaecology",
        "Master of Medicine in Internal Medicine",
        "Master of Medicine in Paediatrics and Child Health",
        "Master of Science in Human Anatomy",
        "Master of Science in Public Health Nutrition",
        "Master of Science in Community Nutrition and Development",
        "Master of Science in Medical Biotechnology",
        "Master of Science in Medical Parasitology",
        "Master of Science in Medical Entomology and Vector Science",
        "Master of Science in Medical Microbiology",
        "Master of Science in Medical Immunology",
        "Master of Science in Medical Cytology and Histology",
        "Master of Science in Medical Haematology",
        "Master of Science in Clinical Chemistry",
        "Master of Science in Pharmaceutical Sciences",
        "Master of Science in Cell and Molecular Biology",
        "Master of Science in Biomedical Science and Technology",
        "Master of Science in Public Health",
        "Master of Science in Medical Physiology",
        "Master of Science in Plant Ecology",
        "Master of Science in Plant Physiology and Biochemistry",
        "Master of Science in Developmental Botany",
        "Master of Science in Genetics",
        "Master of Science in Plant Pathology",
        "Master of Science in Chemistry",
        "Master of Science in Aquatic Resources Conservation and Fisheries Development",
        "Master of Science in Conservation Biology",
        "Master of Science in Applied Entomology",
        "Master of Science in Applied Parasitology and Vector Biology",
        "Master of Science in Molecular Microbiology and Biotechnology",
        "Master of Science in Physics",
        "Master of Science in Botany",
        "Master of Science in Pure Mathematics",
        "Master of Science in Applied Mathematics",
        "Master of Science in Quantitative Research Methods",
        "Master of Science in Applied Statistics",
        "Master of Science in Actuarial Science",
        "Master of Science in Research Methods",
        "Master of Science in Computer Science",
        "Master of Science in Information Technology",
        "Master of Science in Information Systems",
        "Master of Science in Parallel and Distributed Computing",
        "Master of Science in Mobile Computing and Networking",
        "Master of Science in Computer Technology",
        "Master of Science in Communication and Networking",
        "Master of Science in Artificial Intelligence",
        "Master of Public Health (MPH)",
        "Master of Science (MSc) in Quantitative Research Methods",
        "Master of Arts (MA) in Monitoring and Evaluation",
        "Master of Arts (MA) in Project Planning and Management",
        "Master of Arts (MA) in Social Development and Management"
    ],
    "Bachelors": [
        "Bachelor of Science in Animal Science with IT",
        "Bachelor of Science (Environmental Science with IT)",
        "Bachelor of Science in Agricultural Education and Extension (with IT)",
        "Bachelor of Science in Agribusiness Management (with IT)",
        "Bachelor of Science in Agricultural Economics (with IT)",
        "Bachelor of Science in Soil Science and Plant Nutrition with IT",
        "Bachelor of Science with IT",
        "Bachelor of Science in Fisheries and Aquaculture with IT",
        "Bachelor of Science in Aquatic Resource Conservation and Management with IT",
        "Bachelor of Arts in Disaster Management with IT",
        "Bachelor of Science in Geospatial Information Science with IT",
        "Bachelor of Science in Horticulture with IT",
        "Bachelor of Science in Agronomy with IT",
        "Bachelor of Science in Agricultural Economics and Rural Development with IT",
        "Bachelor of Science in Earth Sciences with IT",
        "Bachelor of Arts (Music) with IT and Bachelor of Arts (Drama and Theatre Studies) with IT",
        "Bachelor of Arts in Language and Communication with IT",
        "Bachelor of Arts (Kiswahili) with IT",
        "Bachelor of Arts in Communication Media Technology with IT",
        "Bachelor of Arts in Communication Media Technology with IT",
        "Bachelor of Arts program in Literature",
        "Bachelor of Arts in Criminology",
        "Bachelor of Arts in Anthropology",
        "Bachelor of Arts in Sociology",
        "Bachelor of Arts in History and Archaeology",
        "Bachelor of Arts in Counselling Psychology with Information Technology (IT)",
        "Bachelor of Arts (French) with IT/Bachelor of Education (French with IT)",
        "Bachelor of Arts in Philosophy with IT",
        "Bachelor of Arts in Religion with IT",
        "Bachelor of Arts in Fine Art with IT",
        "Bachelor of Arts in Design (Interior Design with IT)",
        "Bachelor of Arts in Design (Fashion Design with IT)",
        "Bachelor of Science in Geography and Natural Resource Management with IT",
        "Bachelor of Science in Climate Change and Development with IT",
        "Bachelor of Science in Ecotourism Management with IT",
        "Bachelor of Science in Hotel and Institution Management with IT",
        "Bachelor of Arts in Drama and Theatre Studies with IT",
        "Bachelor of Arts in Sociology and Anthropology with IT",
        "Bachelor of Arts in Music with IT",
        "Bachelor of Arts in Textile, Apparel Design and Fashion Merchandise with IT",
        "Bachelor of Arts in Interior Design with IT",
        "Bachelor of Arts in Criminology with IT",
        "Bachelor of Arts in Theology with IT",
        "Bachelor of Arts in Psychology with IT",
        "Bachelor of Arts in English with IT",
        "Bachelor of Arts in Literature with IT",
        "Bachelor of Arts in Kiswahili with IT",
        "Bachelor of Arts in Gender and Development with IT",
        "Bachelor of Business Information Technology",
        "Bachelor of Procurement and Supply Chain Management",
        "Bachelor of Economics and Finance with IT",
        "Bachelor of Economics and Statistics with IT",
        "Bachelor of Applied Economics with IT",
        "Bachelor of Economics with IT",
        "Bachelor of Science in Hotel and Institution Management with IT",
        "Bachelor of Science in Travel and Tourism Management with IT",
        "Bachelor of Business Entrepreneurship with IT",
        "Bachelor of Business Administration with IT (BBA)",
        "Bachelor of Science in Accounting and Finance with IT",
        "Bachelor of Arts in Business Studies with IT",
        "Bachelor of Arts in Economics with IT",
        "Bachelor of Science in Economics and Statistics with IT",
        "Bachelor of Science in Economics and Finance with IT",
        "Bachelor of Science in Computer Science",
        "Bachelor of Science in Information Technology",
        "Bachelor of Science in Information Communications and Technology",
        "Bachelor of Science in Computer Technology",
        "Bachelor of Science in Information Systems",
        "Bachelor of Education in Science (with IT)",
        "Bachelor of Education in Early Childhood Education (with IT)",
        "Bachelor of Education in Primary Education (with IT)",
        "Bachelor of Education in Special Needs Education (with IT)",
        "Bachelor of Education in Psychology",
        "Bachelor of Education (Arts) with IT",
        "Bachelor of Education (Community-Based Rehabilitation) with IT",
        "Bachelor of Education (Home Science) with IT",
        "Bachelor of Arts in International Relations and Diplomacy (with IT)",
        "Bachelor of Arts in Political Science (with IT)",
        "Bachelor of Arts in Development Studies (with IT)",
        "Bachelor of Urban and Regional Planning (with IT)",
        "Bachelor of Disaster Management (with IT)",
        "Bachelor of Geospatial Information Science (with IT)",
        "Bachelor of Pharmacy",
        "Bachelor of Science in Pharmaceutical Sciences with IT",
        "Bachelor of Medicine and Bachelor of Surgery with IT",
        "Bachelor of Medicine in Family and Emergency Medicine",
        "Bachelor of Medicine in General Surgery",
        "Bachelor of Science in Medical Biotechnology with Information Technology (IT)",
        "Bachelor of Science in Nutrition and Dietetics with IT",
        "Bachelor of Science in Health Systems Management with Information Technology",
        "Bachelor of Science in Public Health with Information Technology",
        "Bachelor of Science in Health Records and Information Management with IT",
        "Bachelor of Science in Medical Laboratory Science with IT",
        "Bachelor of Science in Nursing with IT",
        "Bachelor of Science in Analytical Chemistry with IT",
        "Bachelor of Science in Industrial Chemistry with IT",
        "Bachelor of Science in Botany with IT",
        "Bachelor of Science in Ethnobotany and Medicinal Plant Science with IT",
        "Bachelor of Science in Physics with IT",
        "Bachelor of Science in Biochemistry with IT",
        "Bachelor of Science in Applied Statistics with IT",
        "Bachelor of Science in Actuarial Science with IT",
        "Bachelor of Science in Mathematical Science with IT",
        "Bachelor of Science in Mathematics and Business with IT",
        "Bachelor of Science in Mathematics and Economics with IT",
        "Bachelor of Science in Mathematics and Computer Science",
        "Bachelor of Science in Mathematics with IT",
        "Bachelor of Business Administration (with IT)",
        "Bachelor of Science (Actuarial Science, with IT)",
        "Bachelor of Science (Applied Statistics, with IT)",
        "Bachelor of Science (Mathematics and Business Studies, with IT)",
        "Bachelor of Science (Mathematical Science, with IT)",
        "Bachelor of Procurement and Supply Chain Management (with IT)"
    ],
    "Diploma": [
        "Diploma in French (Several Levels)",
        "Diploma in Public Relations",
        "Dipoloma in Theology, Religion",
        "Diploma in Journalism & Mass Media",
        "Diploma in Social Work",
        "Diploma in Literature",
        "Diploma in Conflict Resolution",
        "Diploma in Peace building",
        "Diploma in Film & Theatre Studies",
        "Diploma in Business Administration",
        "Diploma in Small Enterprise Finance",
        "Diploma in Management",
        "Diploma in Purchasing & Supply Management",
        "Diploma in Sales and Marketing",
        "Diploma in Human Resource Management",
        "Diploma in Management of Transport Systems",
        "Diploma in Strategic Management",
        "Diploma in Enterpreneurship",
        "Diploma in Management of NGO's",
        "Diploma in Enterprise Management",
        "Diploma in Health care Economics",
        "Diploma in Project Management",
        "Diploma in E-Commerce & e-Business",
        "Diploma in Hospitality Management",
        "Diploma in Travel and Tourism",
        "Diploma in Enterpreneurship Education",
        "Diploma in Environmental Education",
        "Diploma in Disability",
        "Diploma in Early childhood Education",
        "Diploma in Sign Language",
        "Diploma in Special needs Education",
        "Diploma in Guidance & Counselling",
        "Diploma in School Administration",
        "Diploma in Educational Administration",
        "Diploma in Pedagogical Skills",
        "Diploma in Education Evaluation",
        "Diploma in ICT Application in Education",
        "Diploma in Diplomacy",
        "Diploma in Public Administration",
        "Diploma in Peace And Security Studies",
        "Diploma in Community Development",
        "Diploma in Actuarial Science",
        "Diploma in Information and Communication Technology (DICT)",
        "Diploma in HIV & AIDS Determinants",
        "Diploma in Prevention & Management",
        "Diploma in Health Economics",
        "Diploma in Medical Laboratory & Community Health",
        "Diploma in Urban Management",
        "Diploma in Monitoring & Evaluation",
        "Diploma in Analytical Chemistry"
    ],
    "Certificate": [
        "Certificate in Theology",
        "Certificate in Religion",
        "Certificate in Journalism & Mass Media",
        "Certificate in Social Work",
        "Certificate in Public Relations",
        "Certificate in Theatre Development",
        "Certificate in French (Several Levels)",
        "Certificate in Business Administration",
        "Certificate in Micro Economics",
        "Certificate in Macro Economics",
        "Certificate in Small Enterprise Finance",
        "Certificate in Management",
        "Certificate in Enterprise Development & Management",
        "Certificate in e-Commerce & e-Business Systems",
        "Certificate in Entrepreneurship",
        "Certificate in Sales and Marketing",
        "Certificate in Project design & Implementation",
        "Certificate in Human Resource Management",
        "Certificate in Strategic Purchasing & Supply Management",
        "Certificate in Youth & Women Group Programmes Management",
        "Certificate in Management of Transport System",
        "Certificate in Guidance & Counselling",
        "Certificate in Disability studies",
        "Certificate in Special Needs Education",
        "Certificate in School Administarion",
        "Certificate in Sign Language",
        "Certificate in Braille",
        "Certificate in Special & Inclusive Education",
        "Certificate in Gender & Development in Education",
        "Certificate in Adult Education",
        "Certificate in Entrepreneurship Education",
        "Certificate in ICT Application in Education",
        "Certificate in Education Evaluation",
        "Certificate in Pedagogical Skills",
        "Certificate in Special and Inclusive Education",
        "Certificate in Public Administration",
        "Certificate in Community Development",
        "Certificate in Peace And Security Studies",
        "Certificate in Diplomacy",
        "Certificate in Monitoring & Evaluation",
        "Certificate in Result Based Management",
        "Certificate in Information & Communication Technology",
        "Certicate in Enviromental Impact Assesment (EIA)",
        "Certificate in Climate Change Adaptation",
        "Certicate in Hospitality & Tourism Operations",
        "Certificate in Pre-University Entrance Course"
    ]
}

# Define the header
header = ["Doctorate", "Masters", "Bachelors", "Diploma", "Certificate"]

# Open the CSV file in write mode
with open('msu_all_programs.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    
    # Write the header
    writer.writerow(header)
    
    # Determine the maximum number of programs in any category
    max_len = max(len(programs) for programs in data.values())
    
    # Write the data row by row
    for i in range(max_len):
        row = [
            data["Doctorate"][i] if i < len(data["Doctorate"]) else "",
            data["Masters"][i] if i < len(data["Masters"]) else "",
            data["Bachelors"][i] if i < len(data["Bachelors"]) else "",
            data["Diploma"][i] if i < len(data["Diploma"]) else "",
            data["Certificate"][i] if i < len(data["Certificate"]) else ""
        ]
        writer.writerow(row)

print("CSV file has been created successfully.")
